start: (statement ";")+ 

statement: declaration -> declstate | function -> funcstate

declaration: variable "=" assignment

function: NAME"(" [value+] ")" | NAME"(" [ESCAPED_STRING+] ")"

string: ESCAPED_STRING

variable: NAME

assignment: NUMBER | function | variable | string
value: NUMBER | function | variable | string


%import common.WS
%import common.CNAME -> NAME
%import common.INT -> NUMBER
%import common.ESCAPED_STRING
%ignore WS